rails_app/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, skip: 'sessions', controllers: { 
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [:show], param: :user_id
  namespace :users do
    resource :password, only: [:edit, :update]
    resource :delete_form, only: [:new]
  end

  get  "applicant_entry_recruitings", to: 'applicant_entry_recruitings#index', as: :applicant_entry_recruitings
  resource :applicant_entry_recruitings, only: [:create, :update, :destroy]
  resource :apex_profile,  except: [:show]

  namespace :recruitings do
    get 'search', to: 'search#show', as: :search
  end
  resources :recruitings,  except: [:index]

  resources :notices, only: [:index]
  namespace :notices do
    resource :unread_notice_count, only: [:show]
  end

  resources :comments, only: [:create]

  root "top#show"
end

rails_app/app/models/recruiting.rb
# == Schema Information
#
# Table name: recruitings
#
#  id                   :bigint           not null, primary key
#  comment              :text
#  game_mode            :integer
#  participants_numbers :integer          default(0)
#  play_style           :text
#  rank                 :integer
#  recruitment_numbers  :integer
#  status               :integer          default("open"), not null
#  type                 :string           not null
#  vc                   :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  user_id              :string(32)       not null
#
class Recruiting < ApplicationRecord
  before_update do
     update_status_with_recruitment_numbers if will_save_change_to_recruitment_numbers?
  end

  after_update do
    #更新時に募集が満員、もしくはクローズになった場合、未承認の応募者レコードを全員削除する
    if saved_change_to_status && !self.open?
      cut_the_applicants
    end
  end

  belongs_to :user

  has_many :applicant_entry_recruitings,
             primary_key: :id,
             foreign_key: :entry_recruiting_id,
             dependent: :destroy
  has_many :applicants,
             class_name: "User",
             through: :applicant_entry_recruitings

  has_many :comments,
             dependent: :destroy

  validates :user_id, presence: true, uniqueness: true, length: { maximum: 32 }
  validates :type,  presence: true
  validates :recruitment_numbers,  presence: true
  validates :play_style, length: { maximum: 32 }
  validates :comment, length: { maximum: 255 }

  validate :valid_type?
  validate :validation_recruitment_numbers
  validate :validation_status_update, on: :update

  default_scope -> { order(created_at: :desc) }
  scope :status_open,   -> { where(status: 'open') }
  scope :apex_type,     -> { where(type: 'ApexRecruiting') }



  enum vc: { 
    "off": 0,
    "on": 1
  }


  enum status: { 
    "open": 0,
    "close": 1,
    "filled": 2
  }


  #list of game type.
  GAMETYPENAMES = ['ApexRecruiting']



  def owner?(user)
    user.user_id == self.user.user_id ? true :false
  end


  class << self
    def search(params)
      if params[:search][:type] && GAMETYPENAMES.include?(params[:search][:type])
        game_model = params[:search][:type]
        game_model.constantize.search(params)
      else
        return nil
      end
    end

  end


  private

  def valid_type?
    if type.present? && GAMETYPENAMES.exclude?(type)
      errors.add(:type, " 指定のゲームは募集できません")
    end
  end


  #募集人数更新時は、既に参加しているユーザー数を下回っていないか確認する
  def validation_recruitment_numbers
    #募集人数が無い場合、precenseバリデーションで引っかかるのでここではすぐに返す
    return unless self.recruitment_numbers

    if recruitment_numbers_is_less_than_participants?
      errors.add(:recruitment_numbers, '既に参加しているメンバー数未満の値には設定できません。')
    end
  end

  #募集人数を増加時、もし募集状態が満員(filled)だったら公開中（open）にする
  def update_status_with_recruitment_numbers
    if recruitment_numbers_is_more_than_participants? && self.filled?
      self.status = 'open'
    end
  end


  #募集人数が参加者数以下のまま公開状態への変更はさせない
  def validation_status_update
    #募集人数が無い場合、precenseバリデーションで引っかかるのでここではすぐに返す
    return unless self.recruitment_numbers

    if self.open? && recruitment_numbers_is_no_more_than_participants?
      errors.add(:status, 'この募集は満員状態なので公開できません。募集人数を再設定するか、新しく募集を作成してください')
    end
  end


  #未承認の募集者を全員切る
  def cut_the_applicants
    self.applicant_entry_recruitings.each do |entry|
      
      if entry.unapproved?
        entry.delete_reason = 'refusal'
        entry.destroy
      end
    end
  end

  def recruitment_numbers_is_less_than_participants?
    self.recruitment_numbers < self.participants_numbers ? true : false
  end


  def recruitment_numbers_is_no_more_than_participants?
    self.recruitment_numbers <= self.participants_numbers ? true : false
  end


  def recruitment_numbers_is_more_than_participants?
    self.recruitment_numbers > self.participants_numbers ? true : false
  end
end

rails_app/app/controllers/recruitings/search_controller.rb
class Recruitings::SearchController < ApplicationController
  before_action :authenticate_user!,
                :set_user,
                :set_users_recruiting,
                :set_applying_recruiting


  #今のところはAPEXの募集専用のアクション
  def show

    if search_params.present?
      search_results = Recruiting.search(search_params)
    else
      search_results = Recruiting.status_open
    end

    @search_results_for_view = search_results.page(params[:page]).per(5)

    if search_results
      @search_results_count = search_results.size
    else
      @search_results_count = 0
    end

    
  end


  private

  def search_params
    params.permit(:commit, search: [:type, :rank, :game_mode])
  end


  def set_user
    @user = current_user
  end


  def set_users_recruiting
    @recruiting = @user.recruiting
  end


  def set_applying_recruiting
    @applying_recruiting = @user.entry_recruiting
  end

end

rails_app/app/controllers/recruitings_controller.rb
class RecruitingsController < ApplicationController
  #typeパラメーターが不適切だった場合のエラーハンドリング
  rescue_from ActiveRecord::SubclassNotFound, with: :subclass_not_found

  before_action :authenticate_user!, :set_user
  before_action :set_users_recruiting, except: [:create, :show, :search]
  before_action :set_recruiting, only: [:show]


  def new
    if @recruiting
      redirect_to edit_recruiting_path(@recruiting.id)
    else
      @recruiting = Recruiting.new
    end
  end


  def create
    @recruiting = @user.build_recruiting(recruiting_params)

    if @recruiting.save
      redirect_to recruiting_path(@recruiting)
    else
      render 'new'
    end
  end


  def edit
    if @recruiting.nil?
      redirect_to new_recruiting_path
    end
  end


  def update
    return redirect_to new_recruiting_path if @recruiting.nil?

    if @recruiting.update(recruiting_params)
      redirect_to recruiting_path(@recruiting)
    else
      render 'edit'
    end
  end


  def destroy
    @recruiting.destroy
    redirect_to user_path(@user.user_id)
  end


  def show
    @user_position_for_recruiting = @user.position_in_the_recruiting(@recruiting)
    @comments = @recruiting.comments.page(params[:page]).per(15)
  end





  private

  def recruiting_params
    params.require(:recruiting).permit(:type, :vc, :recruitment_numbers, :play_style, :comment, :rank, :game_mode, :status)
  end


  def search_params
    params.permit(:commit, search: [:type, :rank, :game_mode])
  end


  def set_user
    @user = current_user
  end


  def set_recruiting
    @recruiting = Recruiting.find_by(id: params[:id])
    redirect_to root_path unless @recruiting
  end


  def set_users_recruiting
    @recruiting = @user.recruiting
  end

  #typeパラメータが不適切な場合のエラー処理。この場合、正規フォームからのリクエストでない可能性が高いので、ルートにリダイレクト
  def subclass_not_found(action)
    redirect_to root_path
  end

end

rails_app/app/helpers/recruitings_helper.rb
module RecruitingsHelper
  
  #ログインしているユーザーのポジションに合わせたvueファイルをう埋め込む
  def operation_display_for_position(position)
    packs_for_user = {
      owner:     { pack: 'recruiting/show/operation_for_owner' },
      member:    { pack: 'recruiting/show/operation_for_member' },
      applicant: { pack: 'recruiting/show/operation_for_applicant' },
      free:      { pack: 'recruiting/show/operation_for_general_user' }
    }

    if position === :applicant_for_another_recruiting
      content = content_tag(:div) do
        content_tag(:p, "他の募集に応募しているので、応募はできません。")
      end

    #募集が満員、もしくは閉じていた場合に一般ユーザーがアクセスしてきた場合
    elsif position === :free && !@recruiting.open?
      content = content_tag(:div, class: 'recruiting_show_close_notice') do
        content_tag(:p, "こちらの募集には応募できません。")
      end
    elsif position
      #div to mount vue
      mounted_div_tag = content_tag(:div, nil, id: "recruiting_operation")
      #load js
      js_pack_tag = javascript_pack_tag(packs_for_user[position][:pack])
      content = mounted_div_tag + js_pack_tag
    else
      content = nil
    end

    return content
  end


  def display_recruiting_status
    if @recruiting.open?
      content_tag(:span, "募集中", class: "open")
    elsif @recruiting.close?
      content_tag(:span, "募集終了", class: "close")
    elsif @recruiting.filled?
      content_tag(:span, "満員", class: "filled")
    end
  end


  #文字列をバイト単位で切り抜き、最後に省略記号を追加するメソッド
  def resize_string(str, options = {})
    return nil unless str

    options = { 
      size: 20,
      ellipsis: true 
    }.merge(options)

    byte_size = str.bytesize

    #文字列をカットして不正な文字は削除
    last_index = options[:size] - 1
    str = str.byteslice(0..last_index).scrub('')

    #文字列の最後に省略記号を追加
    str = str + '....' if options[:ellipsis] && byte_size > last_index
    
    return str
  end
end

rails_app/app/views/recruitings/search/show.html.erb
<% content_for(:title, '募集検索') %>
<% content_for :side_menu do %>
  <%= javascript_pack_tag 'side_menu' %>
<% end %>
<div class="recruitings_search">
  <div class="your_section">

    <section class="your_recruiting">
      <h2 class="your_section_ttl">あなたの募集</h2>
      <% if @recruiting %>
        <%= link_to recruiting_path(@recruiting), class: 'your_recruiting_card_link' do%>
          <div class="your_recruiting_card">
            <div class="your_recruiting_left">
              <div class="your_recruiting_left_icon">
                <%= image_tag 'users/show/user_ico.png', alt: '' %>
              </div>
              <p class="your_recruiting_left_name">
                <span class="your_recruiting_left_name_sub">オーナー</span><br>
                <%= @user.user_id %>
              </p>
            </div>
            <div class="your_recruiting_right">
              <table class="your_recruiting_right_table">
                <tr>
                  <th>ランク</th>
                  <td><%= @recruiting.rank %></td>
                </tr>
                <tr>
                  <th>VC</th>
                  <td><%= @recruiting.vc %></td>
                </tr>

                <tr>
                  <th>募集人数</th>
                  <td><%= @recruiting.recruitment_numbers %></td>
                </tr>
                <tr>
                  <th>ゲームモード</th>
                  <td><%= @recruiting.game_mode %></td>
                </tr>
                <tr>
                  <th>募集状態</th>
                  <td>
                    <%= display_recruiting_status %>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        <% end %>
      <% else %>
        <%= link_to new_recruiting_path, class: 'your_recruiting_new_btn' do%>
          新しく募集する
        <% end %>
      <% end %>
    </section>

    <section class="your_recruiting">
      <h2 class="your_section_ttl">応募している募集</h2>
      <% if @applying_recruiting %>
        <%= link_to recruiting_path(@applying_recruiting), class: 'your_recruiting_card_link' do%>
          <div class="your_recruiting_card">
            <div class="your_recruiting_left">
              <div class="your_recruiting_left_icon">
                <%= image_tag 'users/show/user_ico.png', alt: '' %>
              </div>
              <p class="your_recruiting_left_name">
                <span class="your_recruiting_left_name_sub">オーナー</span><br>
                <%= @applying_recruiting.user.user_id %>
              </p>
            </div>
            <div class="your_recruiting_right">
              <table class="your_recruiting_right_table">
                <tr>
                  <th>ランク</th>
                  <td><%= @applying_recruiting.rank %></td>
                </tr>
                <tr>
                  <th>VC</th>
                  <td><%= @applying_recruiting.vc %></td>
                </tr>

                <tr>
                  <th>募集人数</th>
                  <td><%= @applying_recruiting.recruitment_numbers %></td>
                </tr>
                <tr>
                  <th>ゲームモード</th>
                  <td><%= @applying_recruiting.game_mode %></td>
                </tr>
              </table>
            </div>
          </div>
        <% end %>
        <div>
          <p class="your_applying_recruiting_status">
            状態:
            <% if @user.applicant_entry_recruiting.approved? %>
              <span class="status_approve">参加中</span>
            <% else %>
              <span class="status_unapprove">承認待ち</span>
            <% end %>
          </p>
        </div>
      <% else %>
        <p>あなたはどの募集にも応募していません。</p>
      <% end %>
    </section>

  </div>
  <div class="recruitings_search_box">
    <section class="recruitings_search_form">
      <h2 class="recruitings_search_form_ttl">検索条件</h2>
      <%= form_with method: :get, url: recruitings_search_path, scope: :search, local: true do |f| %>
        <div class="recruitings_search_form_fields_wrap">
          <div class="recruitings_search_form_field">
            <label class="recruitings_search_form_select_label" for="search_type">募集するゲーム</label>
            <div class='recruitings_search_form_select'>
              <%= f.select :type, {'Apex Legends': 'ApexRecruiting'},  selected: 'ApexRecruiting'%>
            </div>
          </div>
          <div class="recruitings_search_form_field">
            <label class="recruitings_search_form_select_label" for="search_rank">ランク</label>
            <div class='recruitings_search_form_select'>
              <%= f.select :rank, options_for_select_from_enum(ApexRecruiting, 'rank'), { include_blank: true } %>
            </div>
          </div>
          <div class="recruitings_search_form_field">
            <label class="recruitings_search_form_select_label" for="search_game_mode">ゲームモード</label>
            <div class='recruitings_search_form_select'>
              <%= f.select :game_mode, options_for_select_from_enum(ApexRecruiting, 'game_mode'), { include_blank: true } %>
            </div>
          </div>
        </div>
        <div class="recruitings_search_form_actions">
          <%= f.submit "検索" %>
        </div>
      <% end %>
    </section>
    <section class="recruitings_search_results">
      <h2 class="recruitings_search_results_ttl">
        検索結果 : <span class="recruitings_search_results_ttl_sub"><%= @search_results_count %>件</span>
      </h2>
      <% if @search_results_for_view %>
        <div class="recruitings_search_results_list"> 
          <% @search_results_for_view.includes(:user).each do |recruiting| %>
            <%= link_to recruiting_path(recruiting), class: 'recruitings_search_results_card_link' do%>
              <div class="recruitings_search_results_card">
                <div class="recruitings_search_results_left">
                  <div class="recruitings_search_results_left_icon">
                    <%= image_tag 'users/show/user_ico.png', alt: '' %>
                  </div>
                  <p class="recruitings_search_results_left_name">
                    <span class="recruitings_search_results_left_name_sub">オーナー</span><br>
                    <%= recruiting.user.user_id %>
                  </p>
                </div>
                <div class="recruitings_search_results_right">
                  <table class="recruitings_search_results_right_table">
                    <tr>
                      <th>ランク</th>
                      <td><%= recruiting.rank %></td>
                    </tr>
                    <tr>
                      <th>VC</th>
                      <td><%= recruiting.vc %></td>
                    </tr>

                    <tr>
                      <th>募集人数</th>
                      <td><%= recruiting.recruitment_numbers %></td>
                    </tr>
                    <tr>
                      <th>ゲームモード</th>
                      <td><%= recruiting.game_mode %></td>
                    </tr>
                  </table>
                </div>
                <div class="recruitings_search_results_bottom">
                  <p class="recruitings_search_results_bottom_ttl">コメント</p>
                  <p class="recruitings_search_results_bottom_content"><%= resize_string(recruiting.comment, { size: 200 }) %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="recruitings_search_paginate">
          <%= paginate @search_results_for_view %>
        </div>
      <% end %>
    </section>
  </div>
</div>