rails_app/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, skip: 'sessions', controllers: { 
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [:show], param: :user_id
  namespace :users do
    resource :password, only: [:edit, :update]
    resource :delete_form, only: [:new]
  end

  get  "applicant_entry_recruitings", to: 'applicant_entry_recruitings#index', as: :applicant_entry_recruitings
  resource :applicant_entry_recruitings, only: [:create, :update, :destroy]
  resource :apex_profile,  except: [:show]

  namespace :recruitings do
    get 'search', to: 'search#show', as: :search
  end
  resources :recruitings,  except: [:index]

  resources :notices, only: [:index]
  namespace :notices do
    resource :unread_notice_count, only: [:show]
  end

  resources :comments, only: [:create]

  root "top#show"
end

rails_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  age                    :integer
#  encrypted_password     :string           default(""), not null
#  introduce              :text
#  name                   :string(16)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sex                    :integer          default("男性"), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :string(32)       not null, primary key
#
# Indexes
#
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_user_id               (user_id) UNIQUE
#
class User < ApplicationRecord
  has_one :apex_profile, dependent: :destroy, primary_key: :user_id, foreign_key: :user_id
  has_one :recruiting, dependent: :destroy, primary_key: :user_id, foreign_key: :user_id

  has_one :applicant_entry_recruiting,
            primary_key: :user_id,
            foreign_key: :applicant_id,
            dependent: :destroy
  has_one :entry_recruiting,
            class_name: "Recruiting",
            through: :applicant_entry_recruiting

  has_many :notices,
             dependent: :destroy

  has_many :comments,
             dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :authentication_keys => [:user_id]

  devise :validatable, password_length: 8..128
  validates :user_id, presence: true, uniqueness: true, length: { maximum: 32 }
  validates :name, length: { maximum: 16 }
  validates :introduce, length: { maximum: 255 }


  enum sex: { "男性": 0, "女性": 1}


  #emaiをdeviseで使わない設定
  def email_required?
    false
  end

  #emaiをdeviseで使わない設定
  def email_changed?
    false
  end
  
  #emaiをdeviseで使わない設定（モンキーパッチ）
  def will_save_change_to_email?
    false
  end

  #アップデート時にはパスワードを使用しない
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end


  #引数の募集オブジェクトに対して、ユーザーがどの役割を担っているかシンボルで返すメソッド
  def position_in_the_recruiting(recruiting)
    return false unless recruiting

    applicants = recruiting.applicants

    if self.user_id == recruiting.user_id
      :owner
    elsif applicants.include?(self) && self.applicant_entry_recruiting.approved?
      :member
    elsif applicants.include?(self)
      :applicant
    elsif applicants.exclude?(self) && !self.entry_recruiting
      :free
    else
      :applicant_for_another_recruiting
    end
  end

end

rails_app/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

rails_app/app/controllers/users/delete_forms_controller.rb
class Users::DeleteFormsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user


  def new
  end

  private

  def set_user
    @user = current_user
  end

end

rails_app/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

rails_app/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user


  def edit
  end


  def update
    if @user.update_with_password(user_password_params)
      bypass_sign_in(current_user)
      redirect_to user_path(current_user.user_id)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_password_params
    params.require(:user_password).permit(:password, :password_confirmation, :current_password)
  end

end

rails_app/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
     super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # override because update without password
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :sex, :age, :introduce])
  end

  #The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource.user_id)
  end

  #The path used after sign in.
  def after_sign_in_path_for(resource)
    user_path(resource.user_id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    user_path(resource.user_id)
  end
end

rails_app/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  #GET /resource/sign_in
  #def new
  #  super
  #end

  # POST /resource/sign_in
  #def create
  #  super
  #end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  #The path used after sign in.
  def after_sign_in_path_for(resource)
    user_path(resource.user_id)
  end
end

rails_app/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

rails_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_user, only: [:show]
  
  def show
    redirect_to root_path if @user == nil
  end


  private

  def set_user
    @user = User.find_by(user_id: params[:user_id])
  end

  def user_params
    params.require(:user).permit(:user_id)
  end

end

rails_app/app/helpers/users_helper.rb
module UsersHelper
  
  def edit_icon_link(link)
    return unless user_signed_in?
    
    if current_user.user_id == params[:user_id]
      link_to link, class: 'edit_user_icon_link'  do
        img = image_tag('users/show/edit_ico.png', alt: '')
        img + '編集する'
      end
    end
  end

  def my_page?
    return false unless user_signed_in?
    current_user.user_id == params[:user_id] ? true : false
  end
end

rails_app/app/views/users/show.html.erb
<% content_for(:title, @user.user_id) %>
<% content_for :side_menu do %>
  <%= javascript_pack_tag 'side_menu' %>
<% end %>
<section class="user">
  <div  class="user_profile">
    <div class="user_profile_header">
      <div class="user_profile_header_icon">
        <%= image_tag 'users/show/user_ico.png', alt: '' %>
      </div>
      <h1 class="user_profile_header_name"><%= @user.name %></h1>
      <span class="user_profile_header_id"><%= @user.user_id %></span>
      <div class="user_profile_header_other">
        <span>性別：<%= @user.sex %></span>
        <span>年齢：<%= @user.age %></span>
      </div>
    </div>
    <div class="user_profile_body">
      <section class="user_profile_body_description">
        <% if my_page? && !@user.introduce %>
          <div class="user_profile_body_new_link">
            <p class="user_profile_body_new_link_notes">
              あなたのプロフィールはまだありません。
            </p>
            <%= link_to 'プロフィールを編集する', edit_user_registration_path, class: 'user_profile_body_new_link_anchor' %>
          </div>        
        <% elsif @user.introduce %>
          <h2 class="user_profile_body_ttl">プロフィール<%= edit_icon_link(edit_user_registration_path) %></h2>
          <p class="user_profile_body_description_text">
            <%= @user.introduce %>
          </p>
        <% end %>
      </section>

      <% if my_page? && !@user.apex_profile %>
        <div class="user_profile_body_new_link">
          <p class="user_profile_body_new_link_notes">
            あなたのAPEXプロフィールはまだありません。
          </p>
          <%= link_to 'APEXプロフィールを作成する', new_apex_profile_path, class: 'user_profile_body_new_link_anchor' %>
        </div>        
      <% elsif @user.apex_profile %>
        <section class="user_profile_body_apex_profile">
          <h2 class="user_profile_body_ttl">APEXプロフィール<%= edit_icon_link(edit_apex_profile_path) %></h2>
          <table class="user_profile_body_apex_profile_table">
            <tr>
              <th>ID</th>
              <td><%= @user.apex_profile.apex_id %></td>
            </tr>
            <tr>
              <th>ランク</th>
              <td><%= @user.apex_profile.rank %></td>
            </tr>

            <tr>
              <th>プラットフォーム</th>
              <td><%= @user.apex_profile.platform %></td>
            </tr>
            <tr>
              <th>よく使うレジェンド</th>
              <td>
                <% @user.apex_profile.legends.each do |legend| %>
                  <%= legend.name %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>よく使う武器</th>
              <td>
                <% @user.apex_profile.weapons.each do |legend| %>
                  <%= legend.name %>
                <% end %>
              </td>
            </tr>
          </table>
        </section>
      <% end %>

      
    </div>
  </div>
</section>