rails_app/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, skip: 'sessions', controllers: { 
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [:show], param: :user_id
  namespace :users do
    resource :password, only: [:edit, :update]
    resource :delete_form, only: [:new]
  end

  get  "applicant_entry_recruitings", to: 'applicant_entry_recruitings#index', as: :applicant_entry_recruitings
  resource :applicant_entry_recruitings, only: [:create, :update, :destroy]
  resource :apex_profile,  except: [:show]

  namespace :recruitings do
    get 'search', to: 'search#show', as: :search
  end
  resources :recruitings,  except: [:index]

  resources :notices, only: [:index]
  namespace :notices do
    resource :unread_notice_count, only: [:show]
  end

  resources :comments, only: [:create]

  root "top#show"
end

rails_app/app/models/apex_profile.rb
# == Schema Information
#
# Table name: apex_profiles
#
#  id         :bigint           not null, primary key
#  level      :integer
#  platform   :integer
#  rank       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  apex_id    :string(32)
#  user_id    :string(32)
#
# Indexes
#
#  index_apex_profiles_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.user_id)
#
class ApexProfile < ApplicationRecord
  belongs_to :user
  has_many :favorite_legends
  has_many :legends, through: :favorite_legends

  has_many :favorite_weapons
  has_many :weapons, through: :favorite_weapons

  validates :user_id, presence: true, uniqueness: true, length: { maximum: 32 }
  validates :apex_id, length: { maximum: 32 }
  validates :level, :numericality => { :less_than => 501 }

  enum rank: { 
    "ブロンズ": 0,
    "シルバー": 1,
    "ゴールド": 2,
    "プラチナ": 3,
    "ダイヤ": 4,
    "マスター": 5,
    "プレデター": 6
  }

  enum platform: { 
    "PC": 0,
    "PS4": 1,
    "XBOX": 2
  }

end

rails_app/app/controllers/apex_profiles_controller.rb
class ApexProfilesController < ApplicationController
  before_action :authenticate_user!, :set_user
  before_action :set_apex_profile, only: [:edit, :update, :destroy]

  def new
    if @user.apex_profile
      redirect_to edit_apex_profile_path
    else
      @apex_profile = ApexProfile.new
    end
  end


  def create 
    @apex_profile = @user.build_apex_profile(apex_profile_params)

    if @apex_profile.save
      redirect_to user_path(@user.user_id)
    else
      render 'new'
    end

  end


  def edit
  end


  def update

    if @apex_profile.update(apex_profile_params)
      redirect_to user_path(@user.user_id)
    else
      render 'edit'
    end

  end


  def destroy
    @apex_profile.destroy
    redirect_to user_path(@user.user_id)
  end



  private

  def apex_profile_params
    params.require(:apex_profile).permit(:apex_id, :rank, :level, :platform, { :legend_ids => [], :weapon_ids => [] })
  end

  def set_user
    @user = current_user
  end

  def set_apex_profile
    @apex_profile = @user.apex_profile
    return redirect_to new_apex_profile_path if @apex_profile.nil?
  end
end

rails_app/app/helpers/apex_profiles_helper.rb
module ApexProfilesHelper
  
end

rails_app/app/views/apex_profiles/edit.html.erb
<% content_for(:title, 'APEXプロフィール編集') %>
<section class="apex_profile_edit_form_wrap">
  <div class="apex_profile_edit_form">
    <h1 class="apex_profile_edit_form_ttl">APEXプロフィール編集</h1>
     <div class="apex_profile_edit_form_body">
      <%= form_with model: @apex_profile, url: apex_profile_path, local: true do |f| %>

        <% if @apex_profile.errors.any? %>
          <div class="apex_profile_edit_form_error">
            <ul>
              <% @apex_profile.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="apex_profile_edit_form_field">
          <%= f.text_field :apex_id, class: 'apex_profile_edit_form_text_input', placeholder: " " %>
          <%= f.label :apex_id, class: 'apex_profile_edit_form_text_input_label' %>
        </div>

        <div class="apex_profile_edit_form_field">
          <%= f.label :rank, class: 'apex_profile_edit_form_select_label' %>
          <div class="apex_profile_edit_form_select">
            <%= f.select :rank, options_for_select_from_enum(ApexProfile, 'rank'), { include_blank: true } %>
          </div>
        </div>

        <div class="apex_profile_edit_form_field">
          <%= f.telephone_field :level, class: 'apex_profile_edit_form_text_input', placeholder: " "%>
          <%= f.label :level, class: 'apex_profile_edit_form_text_input_label' %>
        </div>

        <div class="apex_profile_edit_form_field">
          <%= f.label :platform, class: 'apex_profile_edit_form_select_label' %>
          <div class="apex_profile_edit_form_select">
            <%= f.select :platform, options_for_select_from_enum(ApexProfile, 'platform'), { include_blank: true } %>
          </div>
        </div>

        <div class="apex_profile_edit_form_field">
          <%= f.label :favorite_legends, "お気入りのレジェンド", class: 'apex_profile_edit_form_checkbox_label' %>
          <div class="apex_profile_edit_form_checkbox">
            <%= collection_check_boxes(:apex_profile, :legend_ids, Legend.all, :id, :name) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %>
          </div>
        </div>

        <div class="apex_profile_edit_form_field">
          <%= f.label :favorite_weapons, "お気入りの武器", class: 'apex_profile_edit_form_checkbox_label' %>
          <div class="apex_profile_edit_form_checkbox">
            <%= collection_check_boxes(:apex_profile, :weapon_ids, Weapon.all, :id, :name) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %>
          </div>
        </div>

        <div class="apex_profile_edit_form_actions">
          <%= f.submit "更新" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

rails_app/app/views/apex_profiles/new.html.erb
<% content_for(:title, 'APEXプロフィール作成') %>
<section class="apex_profile_new_form_wrap">
  <div class="apex_profile_new_form">
    <h1 class="apex_profile_new_form_ttl">APEXプロフィール作成</h1>
     <div class="apex_profile_new_form_body">
      <%= form_with model: @apex_profile, url: apex_profile_path, local: true do |f| %>
        
        <% if @apex_profile.errors.any? %>
          <div class="apex_profile_new_form_error">
            <ul>
              <% @apex_profile.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="apex_profile_new_form_field">
          <%= f.text_field :apex_id, class: 'apex_profile_new_form_text_input', placeholder: " " %>
          <%= f.label :apex_id, class: 'apex_profile_new_form_text_input_label' %>
        </div>

        <div class="apex_profile_new_form_field">
          <%= f.label :rank, class: 'apex_profile_new_form_select_label' %>
          <div class="apex_profile_new_form_select">
            <%= f.select :rank, options_for_select_from_enum(ApexProfile, 'rank'), { include_blank: true } %>
          </div>
        </div>

        <div class="apex_profile_new_form_field">
          <%= f.telephone_field :level, class: 'apex_profile_new_form_text_input', placeholder: " "%>
          <%= f.label :level, class: 'apex_profile_new_form_text_input_label' %>
        </div>

        <div class="apex_profile_new_form_field">
          <%= f.label :platform, class: 'apex_profile_new_form_select_label' %>
          <div class="apex_profile_new_form_select">
            <%= f.select :platform, options_for_select_from_enum(ApexProfile, 'platform'), { include_blank: true } %>
          </div>
        </div>

        <div class="apex_profile_new_form_field">
          <%= f.label :favorite_legends, "お気入りのレジェンド", class: 'apex_profile_new_form_checkbox_label' %>
          <div class="apex_profile_new_form_checkbox">
            <%= collection_check_boxes(:apex_profile, :legend_ids, Legend.all, :id, :name) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %>
          </div>
        </div>

        <div class="apex_profile_new_form_field">
          <%= f.label :favorite_weapons, "お気入りの武器", class: 'apex_profile_new_form_checkbox_label' %>
          <div class="apex_profile_new_form_checkbox">
            <%= collection_check_boxes(:apex_profile, :weapon_ids, Weapon.all, :id, :name) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %>
          </div>
        </div>

        <div class="apex_profile_new_form_actions">
          <%= f.submit "作成" %>
        </div>
      <% end %>
    </div>
  </div>
</section>