rails_app/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, skip: 'sessions', controllers: { 
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_in', to: 'users/sessions#create', as: :user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :users, only: [:show], param: :user_id
  namespace :users do
    resource :password, only: [:edit, :update]
    resource :delete_form, only: [:new]
  end

  get  "applicant_entry_recruitings", to: 'applicant_entry_recruitings#index', as: :applicant_entry_recruitings
  resource :applicant_entry_recruitings, only: [:create, :update, :destroy]
  resource :apex_profile,  except: [:show]

  namespace :recruitings do
    get 'search', to: 'search#show', as: :search
  end
  resources :recruitings,  except: [:index]

  resources :notices, only: [:index]
  namespace :notices do
    resource :unread_notice_count, only: [:show]
  end

  resources :comments, only: [:create]

  root "top#show"
end

rails_app/app/models/recruiting.rb
# == Schema Information
#
# Table name: recruitings
#
#  id                   :bigint           not null, primary key
#  comment              :text
#  game_mode            :integer
#  participants_numbers :integer          default(0)
#  play_style           :text
#  rank                 :integer
#  recruitment_numbers  :integer
#  status               :integer          default("open"), not null
#  type                 :string           not null
#  vc                   :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  user_id              :string(32)       not null
#
class Recruiting < ApplicationRecord
  before_update do
     update_status_with_recruitment_numbers if will_save_change_to_recruitment_numbers?
  end

  after_update do
    #更新時に募集が満員、もしくはクローズになった場合、未承認の応募者レコードを全員削除する
    if saved_change_to_status && !self.open?
      cut_the_applicants
    end
  end

  belongs_to :user

  has_many :applicant_entry_recruitings,
             primary_key: :id,
             foreign_key: :entry_recruiting_id,
             dependent: :destroy
  has_many :applicants,
             class_name: "User",
             through: :applicant_entry_recruitings

  has_many :comments,
             dependent: :destroy

  validates :user_id, presence: true, uniqueness: true, length: { maximum: 32 }
  validates :type,  presence: true
  validates :recruitment_numbers,  presence: true
  validates :play_style, length: { maximum: 32 }
  validates :comment, length: { maximum: 255 }

  validate :valid_type?
  validate :validation_recruitment_numbers
  validate :validation_status_update, on: :update

  default_scope -> { order(created_at: :desc) }
  scope :status_open,   -> { where(status: 'open') }
  scope :apex_type,     -> { where(type: 'ApexRecruiting') }



  enum vc: { 
    "off": 0,
    "on": 1
  }


  enum status: { 
    "open": 0,
    "close": 1,
    "filled": 2
  }


  #list of game type.
  GAMETYPENAMES = ['ApexRecruiting']



  def owner?(user)
    user.user_id == self.user.user_id ? true :false
  end


  class << self
    def search(params)
      if params[:search][:type] && GAMETYPENAMES.include?(params[:search][:type])
        game_model = params[:search][:type]
        game_model.constantize.search(params)
      else
        return nil
      end
    end

  end


  private

  def valid_type?
    if type.present? && GAMETYPENAMES.exclude?(type)
      errors.add(:type, " 指定のゲームは募集できません")
    end
  end


  #募集人数更新時は、既に参加しているユーザー数を下回っていないか確認する
  def validation_recruitment_numbers
    #募集人数が無い場合、precenseバリデーションで引っかかるのでここではすぐに返す
    return unless self.recruitment_numbers

    if recruitment_numbers_is_less_than_participants?
      errors.add(:recruitment_numbers, '既に参加しているメンバー数未満の値には設定できません。')
    end
  end

  #募集人数を増加時、もし募集状態が満員(filled)だったら公開中（open）にする
  def update_status_with_recruitment_numbers
    if recruitment_numbers_is_more_than_participants? && self.filled?
      self.status = 'open'
    end
  end


  #募集人数が参加者数以下のまま公開状態への変更はさせない
  def validation_status_update
    #募集人数が無い場合、precenseバリデーションで引っかかるのでここではすぐに返す
    return unless self.recruitment_numbers

    if self.open? && recruitment_numbers_is_no_more_than_participants?
      errors.add(:status, 'この募集は満員状態なので公開できません。募集人数を再設定するか、新しく募集を作成してください')
    end
  end


  #未承認の募集者を全員切る
  def cut_the_applicants
    self.applicant_entry_recruitings.each do |entry|
      
      if entry.unapproved?
        entry.delete_reason = 'refusal'
        entry.destroy
      end
    end
  end

  def recruitment_numbers_is_less_than_participants?
    self.recruitment_numbers < self.participants_numbers ? true : false
  end


  def recruitment_numbers_is_no_more_than_participants?
    self.recruitment_numbers <= self.participants_numbers ? true : false
  end


  def recruitment_numbers_is_more_than_participants?
    self.recruitment_numbers > self.participants_numbers ? true : false
  end
end

rails_app/app/controllers/recruitings/search_controller.rb
class Recruitings::SearchController < ApplicationController
  before_action :authenticate_user!,
                :set_user,
                :set_users_recruiting,
                :set_applying_recruiting


  #今のところはAPEXの募集専用のアクション
  def show

    if search_params.present?
      search_results = Recruiting.search(search_params)
    else
      search_results = Recruiting.status_open
    end

    @search_results_for_view = search_results.page(params[:page]).per(5)

    if search_results
      @search_results_count = search_results.size
    else
      @search_results_count = 0
    end

    
  end


  private

  def search_params
    params.permit(:commit, search: [:type, :rank, :game_mode])
  end


  def set_user
    @user = current_user
  end


  def set_users_recruiting
    @recruiting = @user.recruiting
  end


  def set_applying_recruiting
    @applying_recruiting = @user.entry_recruiting
  end

end

rails_app/app/controllers/recruitings_controller.rb
class RecruitingsController < ApplicationController
  #typeパラメーターが不適切だった場合のエラーハンドリング
  rescue_from ActiveRecord::SubclassNotFound, with: :subclass_not_found

  before_action :authenticate_user!, :set_user
  before_action :set_users_recruiting, except: [:create, :show, :search]
  before_action :set_recruiting, only: [:show]


  def new
    if @recruiting
      redirect_to edit_recruiting_path(@recruiting.id)
    else
      @recruiting = Recruiting.new
    end
  end


  def create
    @recruiting = @user.build_recruiting(recruiting_params)

    if @recruiting.save
      redirect_to recruiting_path(@recruiting)
    else
      render 'new'
    end
  end


  def edit
    if @recruiting.nil?
      redirect_to new_recruiting_path
    end
  end


  def update
    return redirect_to new_recruiting_path if @recruiting.nil?

    if @recruiting.update(recruiting_params)
      redirect_to recruiting_path(@recruiting)
    else
      render 'edit'
    end
  end


  def destroy
    @recruiting.destroy
    redirect_to user_path(@user.user_id)
  end


  def show
    @user_position_for_recruiting = @user.position_in_the_recruiting(@recruiting)
    @comments = @recruiting.comments.page(params[:page]).per(15)
  end





  private

  def recruiting_params
    params.require(:recruiting).permit(:type, :vc, :recruitment_numbers, :play_style, :comment, :rank, :game_mode, :status)
  end


  def search_params
    params.permit(:commit, search: [:type, :rank, :game_mode])
  end


  def set_user
    @user = current_user
  end


  def set_recruiting
    @recruiting = Recruiting.find_by(id: params[:id])
    redirect_to root_path unless @recruiting
  end


  def set_users_recruiting
    @recruiting = @user.recruiting
  end

  #typeパラメータが不適切な場合のエラー処理。この場合、正規フォームからのリクエストでない可能性が高いので、ルートにリダイレクト
  def subclass_not_found(action)
    redirect_to root_path
  end

end

rails_app/app/helpers/recruitings_helper.rb
module RecruitingsHelper
  
  #ログインしているユーザーのポジションに合わせたvueファイルをう埋め込む
  def operation_display_for_position(position)
    packs_for_user = {
      owner:     { pack: 'recruiting/show/operation_for_owner' },
      member:    { pack: 'recruiting/show/operation_for_member' },
      applicant: { pack: 'recruiting/show/operation_for_applicant' },
      free:      { pack: 'recruiting/show/operation_for_general_user' }
    }

    if position === :applicant_for_another_recruiting
      content = content_tag(:div) do
        content_tag(:p, "他の募集に応募しているので、応募はできません。")
      end

    #募集が満員、もしくは閉じていた場合に一般ユーザーがアクセスしてきた場合
    elsif position === :free && !@recruiting.open?
      content = content_tag(:div, class: 'recruiting_show_close_notice') do
        content_tag(:p, "こちらの募集には応募できません。")
      end
    elsif position
      #div to mount vue
      mounted_div_tag = content_tag(:div, nil, id: "recruiting_operation")
      #load js
      js_pack_tag = javascript_pack_tag(packs_for_user[position][:pack])
      content = mounted_div_tag + js_pack_tag
    else
      content = nil
    end

    return content
  end


  def display_recruiting_status
    if @recruiting.open?
      content_tag(:span, "募集中", class: "open")
    elsif @recruiting.close?
      content_tag(:span, "募集終了", class: "close")
    elsif @recruiting.filled?
      content_tag(:span, "満員", class: "filled")
    end
  end


  #文字列をバイト単位で切り抜き、最後に省略記号を追加するメソッド
  def resize_string(str, options = {})
    return nil unless str

    options = { 
      size: 20,
      ellipsis: true 
    }.merge(options)

    byte_size = str.bytesize

    #文字列をカットして不正な文字は削除
    last_index = options[:size] - 1
    str = str.byteslice(0..last_index).scrub('')

    #文字列の最後に省略記号を追加
    str = str + '....' if options[:ellipsis] && byte_size > last_index
    
    return str
  end
end

rails_app/app/views/recruitings/edit.html.erb
<% content_for(:title, '募集内容変更') %>
<section class="recruiting_edit_form_wrap">
  <div class="recruiting_edit_form">
    <h1 class="recruiting_edit_form_ttl">募集内容変更</h1>
    <div class="recruiting_edit_form_body">    

      <%= form_with model: @recruiting, url: recruiting_path, scope: :recruiting, local: true do |f| %>

          <% if @recruiting.errors.any? %>
            <div class="recruiting_edit_form_error">
              <ul>
                <% @recruiting.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

        <div class="recruiting_edit_form_field">
          <%= f.label :type, class: 'recruiting_edit_form_select_label' %>
          <div class='recruiting_edit_form_select'>
            <%= f.select :type, {'Apex Legends': 'ApexRecruiting'},  selected: 'ApexRecruiting'%>
          </div>
        </div>

        <div class="recruiting_edit_form_field">
          <%= f.label :vc, class: 'recruiting_edit_form_select_label' %>
          <div class='recruiting_edit_form_select'>
            <%= f.select :vc, options_for_select_from_enum(Recruiting, 'vc'), { include_blank: '未選択'} %>
          </div>
        </div>

        <div class="recruiting_edit_form_field">
          <%= f.label :recruitment_numbers, class: 'recruiting_edit_form_select_label' %>
          <div class='recruiting_edit_form_select'>
            <%= f.select :recruitment_numbers, {'1人': 1, '2人': 2, '3人': 3}, { include_blank: '未選択'} %>
          </div>
        </div>

        <div class="recruiting_edit_form_field">
          <%= f.text_field :play_style, class: 'recruiting_edit_form_text_input', placeholder: " " %>
          <%= f.label :play_style, class: 'recruiting_edit_form_text_input_label' %>
        </div>

        <div class="recruiting_edit_form_field">
          <%= f.text_area :comment, class: 'recruiting_edit_form_text_area', placeholder: " " %>
          <%= f.label :comment, class: 'recruiting_edit_form_text_area_label' %>
        </div>

        <div class="recruiting_edit_form_field">
          <%= f.label :rank, class: 'recruiting_edit_form_select_label' %>
          <div class='recruiting_edit_form_select'>
            <%= f.select :rank, options_for_select_from_enum(ApexRecruiting, 'rank'), { include_blank: true } %>
          </div>
        </div>

        <div class="recruiting_edit_form_field">
          <%= f.label :game_mode, class: 'recruiting_edit_form_select_label' %>
          <div class='recruiting_edit_form_select'>
            <%= f.select :game_mode, options_for_select_from_enum(ApexRecruiting, 'game_mode'), { include_blank: true } %>
          </div>
        </div>

        <div class="recruiting_edit_form_field">
          <%= f.label :status, class: 'recruiting_edit_form_select_label' %>
          <div class='recruiting_edit_form_select'>
            <%= f.select :status, {'募集を公開する': 'open', '募集を閉じる': 'close' } %>
          </div>
        </div>

        <div class="recruiting_edit_form_actions">
          <%= f.submit "更新する" %>
        </div>

      <% end %>
    </div>
  </div>
</section>

rails_app/app/views/recruitings/new.html.erb
<% content_for(:title, '募集作成') %>
<section class="recruiting_new_form_wrap">
  <div class="recruiting_new_form">
    <h1 class="recruiting_new_form_ttl">募集作成</h1>
    <div class="recruiting_new_form_body">    

      <%= form_with model: @recruiting, url: recruitings_path, scope: :recruiting, local: true do |f| %>

          <% if @recruiting.errors.any? %>
            <div class="recruiting_new_form_error">
              <ul>
                <% @recruiting.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

        <div class="recruiting_new_form_field">
          <%= f.label :type, class: 'recruiting_new_form_select_label' %>
          <div class='recruiting_new_form_select'>
            <%= f.select :type, {'Apex Legends': 'ApexRecruiting'},  selected: 'ApexRecruiting'%>
          </div>
        </div>

        <div class="recruiting_new_form_field">
          <%= f.label :vc, class: 'recruiting_new_form_select_label' %>
          <div class='recruiting_new_form_select'>
            <%= f.select :vc, options_for_select_from_enum(Recruiting, 'vc'), { include_blank: '未選択'} %>
          </div>
        </div>

        <div class="recruiting_new_form_field">
          <%= f.label :recruitment_numbers, class: 'recruiting_new_form_select_label' %>
          <div class='recruiting_new_form_select'>
            <%= f.select :recruitment_numbers, {'1人': 1, '2人': 2, '3人': 3}, { include_blank: '未選択'} %>
          </div>
        </div>

        <div class="recruiting_new_form_field">
          <%= f.text_field :play_style, class: 'recruiting_new_form_text_input', placeholder: " " %>
          <%= f.label :play_style, class: 'recruiting_new_form_text_input_label' %>
        </div>

        <div class="recruiting_new_form_field">
          <%= f.text_area :comment, class: 'recruiting_new_form_text_area', placeholder: " " %>
          <%= f.label :comment, class: 'recruiting_new_form_text_area_label' %>
        </div>

        <div class="recruiting_new_form_field">
          <%= f.label :rank, class: 'recruiting_new_form_select_label' %>
          <div class='recruiting_new_form_select'>
            <%= f.select :rank, options_for_select_from_enum(ApexRecruiting, 'rank'), { include_blank: true } %>
          </div>
        </div>

        <div class="recruiting_new_form_field">
          <%= f.label :game_mode, class: 'recruiting_new_form_select_label' %>
          <div class='recruiting_new_form_select'>
            <%= f.select :game_mode, options_for_select_from_enum(ApexRecruiting, 'game_mode'), { include_blank: true } %>
          </div>
        </div>

        <div class="recruiting_new_form_actions">
          <%= f.submit "募集する" %>
        </div>

      <% end %>
    </div>
  </div>
</section>

rails_app/app/views/recruitings/show.html.erb
<% content_for(:title, @recruiting.user.user_id + 'の募集') %>
<% content_for :side_menu do %>
  <%= javascript_pack_tag 'side_menu' %>
<% end %>
<section class="recruiting_show">
  <div class="recruiting_show_inner">
    <h1 class="recruiting_show_ttl">
      <%= @recruiting.user.user_id %>の募集
    </h1>
    <div class="recruiting_show_detail">
      <div class="recruiting_show_detail_user">
        <%= link_to user_path(@recruiting.user), class: 'recruiting_show_detail_user_link' do%>
          <div class="recruiting_show_detail_user_icon">
            <%= image_tag 'users/show/user_ico.png', alt: '' %>
          </div>
          <span class="recruiting_show_detail_user_name">
            <%= @recruiting.user.name %>
          </span>
        <% end %>
      </div>
      <div class="recruiting_show_detail_conditions">
        <table class="recruiting_show_detail_conditions_table">
          <tr>
            <th>ランク</th>
            <td><%= @recruiting.rank %></td>
          </tr>
          <tr>
            <th>VC</th>
            <td><%= @recruiting.vc %></td>
          </tr>

          <tr>
            <th>募集人数</th>
            <td><%= @recruiting.recruitment_numbers %></td>
          </tr>
          <tr>
            <th>ゲームモード</th>
            <td><%= @recruiting.game_mode %></td>
          </tr>
          <tr>
            <th>募集状態</th>
            <td>
              <%= display_recruiting_status %>
            </td>
          </tr>
        </table>
      </div>
      <section class="recruiting_show_detail_play_style">
        <h2 class="recruiting_show_detail_play_style_ttl">プレイスタイル</h2>
        <p class="recruiting_show_detail_play_style_p"><%= @recruiting.play_style %></p>
      </section>
      <section class="recruiting_show_detail_comment">
        <h2 class="recruiting_show_detail_comment_ttl">コメント</h2>
        <p class="recruiting_show_detail_comment_p"><%= @recruiting.comment %></p>
      </section>
      <% if @user_position_for_recruiting === :owner%>
        <div class="recruiting_show_owner_section">
          <%= link_to edit_recruiting_path(@recruiting), class: 'recruiting_show_owner_section_btn', data: { confirm: "募集を取り消しますか？" } do %>
            <%= image_tag('users/show/edit_ico.png', alt: '') %>
            編集する
          <% end %>
          <div class="recruiting_show_owner_section_btn_delete">
            <%= image_tag('common/trash_can_ico.png', alt: '') %>
            <%= button_to "募集を取り消す", recruiting_path(@recruiting), data: { confirm: "本当に取り消しますか？" }, method: :delete %>
          </div>
        </div>
      <% end %>
    </div>
    <%= operation_display_for_position(@user_position_for_recruiting) %>
    <% if @user_position_for_recruiting === :owner || @user_position_for_recruiting === :member %>
      <section class="recruiting_show_comments">
        <h2 class="recruiting_show_comments_ttl">チャット欄</h2>
        <div class="recruiting_show_comments_list_wrap">
          <ul class="recruiting_show_comments_list">
            <% @comments.includes(:user).each do |comment| %>
              <li>
                <div class="recruiting_show_comments_list_user">
                  <%= link_to user_path(comment.user), class: 'recruiting_show_comments_list_user_link' do%>
                    <div class="recruiting_show_comments_list_user_icon">
                      <%= image_tag 'users/show/user_ico.png', alt: '' %>
                    </div>
                  <% end %>
                  <span class="recruiting_show_comments_list_user_name">
                    <%= comment.user.user_id %>
                  </span>
                  <span class="recruiting_show_comments_list_user_date"><%= l comment.created_at %></span>
                </div>
                <div class="recruiting_show_comments_list_content">
                  <p><%= comment.content %></p>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="recruiting_show_comments_pagenate">
          <%= paginate @comments %>
        </div>
        <div id="recruiting_show_mounted_comment_form" class="recruiting_show_comment_form">
          <%= js_pack_tag = javascript_pack_tag('recruiting/show/comment_form') %>
        </div>
      </section>
    <% end %>
    </div>
  </div>
</section>